### ISSUE TITLE
css options

### ISSUE THREAD

**Issue by Gitby-Leo** [thearchitgarg/html-webpack-injector#5]
thanks for your plugin that's work well，but when inserting ".css"，it’s still in body.
so could you update some code or `options` to support it in next version，like :
`if ((chunk.attributes.src && chunk.attributes.src.includes("_head")) || chunk.attributes.href) {`
Then to push css chunk to headChunks

**Comment by AlanZou007** [comment]
I also want this

**Comment by thearchitgarg** [comment]
This issue is solved in the latest release.
