### ISSUE TITLE
Without a callback, the package will be interrupted.

### ISSUE THREAD

**Issue by yayalovee** [thearchitgarg/html-webpack-injector#6]
![image](https://user-images.githubusercontent.com/28685649/59755602-cd73c700-92ba-11e9-86c4-92f25e8bdf7b.png)

**Comment by thearchitgarg** [comment]
Thanks for pointing this out. 
But package will not be interrupted with a null callback.
Have a look at the example code at [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) itself.

![image](https://user-images.githubusercontent.com/42277837/64664112-bf71b480-d46b-11e9-993e-7ab465763a4c.png)
